#ifndef STM32_CONF_H
#define STM32_CONF_H

#define STM32_DEBUG

//#define INSTRUCTION_CACHE_ENABLE
//#define DATA_CACHE_ENABLE
//#define PREFETCH_ENABLE

//#define STM32_USE_FLASH
#define STM32_USE_UART
#define STM32_USE_SPI
//#define STM32_USE_SD
//#define STM32_USE_SDRAM
//#define STM32_USE_RTC
//#define STM32_USE_DMA
//#define STM32_USE_EXTI
//#define STM32_USE_USB

#ifdef STM32_USE_UART
#define UART_BUF_SIZE 128
#define STM32_USE_UART1
#define STM32_USE_UART2
//#define STM32_USE_UART3
//#define STM32_USE_UART4
//#define STM32_USE_UART5
//#define STM32_USE_UART6
//#define STM32_USE_UART7
//#define STM32_USE_UART8
#endif

#ifdef STM32_USE_SPI
#define STM32_USE_SPI1
//#define STM32_USE_SPI2
//#define STM32_USE_SPI3
//#define STM32_USE_SPI4
//#define STM32_USE_SPI5
//#define STM32_USE_SPI6
#endif

#ifdef STM32_USE_EXTI
//#define STM32_USE_EXTI0
//#define STM32_USE_EXTI1
//#define STM32_USE_EXTI2
//#define STM32_USE_EXTI3
//#define STM32_USE_EXTI4
//#define STM32_USE_EXTI9_5
//#define STM32_USE_EXTI15_10
#endif

#ifdef STM32_USE_DMA
//#define STM32_USE_DMA1_STREAM0
//#define STM32_USE_DMA1_STREAM1
//#define STM32_USE_DMA1_STREAM2
//#define STM32_USE_DMA1_STREAM3
//#define STM32_USE_DMA1_STREAM4
//#define STM32_USE_DMA1_STREAM5
//#define STM32_USE_DMA1_STREAM6
//#define STM32_USE_DMA1_STREAM7
//#define STM32_USE_DMA2_STREAM0
//#define STM32_USE_DMA2_STREAM1
//#define STM32_USE_DMA2_STREAM2
//#define STM32_USE_DMA2_STREAM3
//#define STM32_USE_DMA2_STREAM4
//#define STM32_USE_DMA2_STREAM5
//#define STM32_USE_DMA2_STREAM6
//#define STM32_USE_DMA2_STREAM7
#endif

#ifdef STM32_USE_USB
//#define STM32_USE_USB_HS
//#define STM32_USE_USB_FS

//#define STM32_USB_PWR_FS_PORT gpiob
//#define STM32_USB_PWR_FS_PIN GPIO_PIN_8
//#define STM32_USB_PWR_HS_PORT gpiob
//#define STM32_USB_PWR_HS_PIN GPIO_PIN_8
#endif

/* Clock settings */
//#define STM32_USE_HSE
//#define STM32_HSE_STATE RCC_CR_HSEON
#define STM32_USE_HSI
#define STM32_HSI_STATE RCC_CR_HSION
#define STM32_HSI_CALIBRATION 0x10
#define STM32_USE_LSI
#define STM32_LSI_STATE RCC_CSR_LSION
//#define STM32_USE_LSE
//#define STM32_LSE_STATE RCC_BDCR_LSEON
#define STM32_USE_PLL
#define STM32_PLL_STATE RCC_PLL_ON
#define STM32_PLL_SOURCE RCC_PLLSOURCE_HSI_DIV2
#define STM32_PLLM RCC_CFGR_PLLMULL16
#define STM32_PLLN 1
#define STM32_PLLP RCC_PLLP_DIV1
#define STM32_PLLQ 1
#define STM32_CLOCK_TYPE (RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2)
#define STM32_CLOCK_AHB_DIV RCC_CFGR_HPRE_DIV1
#define STM32_CLOCK_SYSCLK_SOURCE RCC_CFGR_SW_PLL
#define STM32_CLOCK_APB1_DIV RCC_CFGR_PPRE1_DIV2
#define STM32_CLOCK_APB2_DIV RCC_CFGR_PPRE2_DIV1
//#define STM32_FLASH_LAT FLASH_ACR_LATENCY_5WS
//#define STM32_USE_CSE

/* UART settings */
#define STM32_BRATE_UART1 115200
#define STM32_BRATE_UART2 9600
#define STM32_BRATE_UART3 115200
#define STM32_BRATE_UART6 115200
#define STM32_UART_STOPBITS UART_STOPBITS_1
#define STM32_UART_WORDLENGTH UART_WORDLENGTH_8B
#define STM32_UART_PARITY UART_PARITY_NONE
#define STM32_UART_MODE_IT_ENABLE
#define STM32_UART_MODE_DMA_ENABLE

/* Power settings */
#define STM32_PVD_MODE (PVD_MODE_IT | PVD_RISING_EDGE | PVD_FALLING_EDGE)

/* Priority groups */
#define STM32_PRIORITY_SYSCLK NVIC_PRIORITYGROUP_4

/* SDRAM settings */
#define STM32_SDRAM_SIZE_MB 16

//#define STM32_SDRAM_BANK1
//#define STM32_SDRAM_BANK2
#define STM32_SDRAM_COLUMNS FMC_SDRAM_COLUMN_BITS_NUM_9
#define STM32_SDRAM_ROWS FMC_SDRAM_ROW_BITS_NUM_12
#define STM32_SDRAM_BUS_WIDTH FMC_SDRAM_MEM_BUS_WIDTH_16
#define STM32_SDRAM_BANKS FMC_SDRAM_INTERN_BANKS_NUM_4
#define STM32_SDRAM_CAS_LAT FMC_SDRAM_CAS_LATENCY_3
#define STM32_SDRAM_CAS_LAT_MR SDRAM_MODEREG_CAS_LATENCY_3
#define STM32_SDRAM_WP FMC_SDRAM_WRITE_PROTECTION_DISABLE
#define STM32_SDRAM_CLOCK FMC_SDRAM_CLOCK_PERIOD_2
#define STM32_SDRAM_BURST FMC_SDRAM_RBURST_ENABLE
#define STM32_SDRAM_PIPE_DELAY FMC_SDRAM_RPIPE_DELAY_0
#define STM32_SDRAM_LOAD_TO_ACTIVE_DELAY 2
#define STM32_SDRAM_EXIT_SELF_REFRESH_DELAY 7
#define STM32_SDRAM_SELF_REFRESH_TIME 4
#define STM32_SDRAM_ROW_CYCLE_DELAY 6
#define STM32_SDRAM_WRITE_RECOVERY_TIME 2
#define STM32_SDRAM_RP_DELAY 2
#define STM32_SDRAM_RCD_DELAY 2
#define STM32_SDRAM_REFRESH_RATE 0x077d   /* SDRAM refresh counter (90MHz SD clock) */
#define STM32_SDRAM_BURST_LENGTH SDRAM_MODEREG_BURST_LENGTH_2

/* FATFS configurstion */
//#define STM32_FATFS_USE
#define STM32_FATFS_CARD_DETECT_PORT gpiod
#define STM32_FATFS_CARD_EN_CLK enable_clk_GPIOD
#define STM32_FATFS_CARD_DETECT_PIN GPIO_PIN_3
#define STM32_FATFS_BUS_4BITS 1
#define STM32_FATFS_DRIVER SDDriver
#define STM32_FATFS_DRIVER_INC "sddriver.h"

#define STM32_SDIO_BUS SDIO_CLKCR_WIDBUS_0
#define STM32_SDIO_CLOCK_DIV 0

/* SPI configuraion */
// SPI1
#define STM32_SPI1_MODE SPI_MODE_SLAVE
#define STM32_SPI1_DIRECTION SPI_DIRECTION_2LINES
#define STM32_SPI1_DATA_SIZE SPI_DATASIZE_8BIT
#define STM32_SPI1_CLK_POL SPI_POLARITY_LOW
#define STM32_SPI1_CLK_PH SPI_PHASE_1EDGE
#define STM32_SPI1_NSS SPI_NSS_HARD_OUTPUT
#define STM32_SPI1_BRP SPI_BAUDRATEPRESCALER_256
#define STM32_SPI1_FIRST_BIT SPI_FIRSTBIT_MSB
#define STM32_SPI1_TI_MODE SPI_TIMODE_DISABLE
#define STM32_SPI1_CRC SPI_CRCCALCULATION_DISABLE
#define STM32_SPI1_CRC_POL 10
// SPI5
#define STM32_SPI5_MODE SPI_MODE_MASTER
#define STM32_SPI5_DIRECTION SPI_DIRECTION_2LINES
#define STM32_SPI5_DATA_SIZE SPI_DATASIZE_8BIT
#define STM32_SPI5_CLK_POL SPI_POLARITY_LOW
#define STM32_SPI5_CLK_PH SPI_PHASE_1EDGE
#define STM32_SPI5_NSS SPI_NSS_HARD_OUTPUT
#define STM32_SPI5_BRP SPI_BAUDRATEPRESCALER_256
#define STM32_SPI5_FIRST_BIT SPI_FIRSTBIT_MSB
#define STM32_SPI5_TI_MODE SPI_TIMODE_DISABLE
#define STM32_SPI5_CRC SPI_CRCCALCULATION_DISABLE
#define STM32_SPI5_CRC_POL 10
// SPI6
#define STM32_SPI6_MODE SPI_MODE_MASTER
#define STM32_SPI6_DIRECTION SPI_DIRECTION_2LINES
#define STM32_SPI6_DATA_SIZE SPI_DATASIZE_8BIT
#define STM32_SPI6_CLK_POL SPI_POLARITY_LOW
#define STM32_SPI6_CLK_PH SPI_PHASE_1EDGE
#define STM32_SPI6_NSS SPI_NSS_SOFT
#define STM32_SPI6_BRP SPI_BAUDRATEPRESCALER_256
#define STM32_SPI6_FIRST_BIT SPI_FIRSTBIT_MSB
#define STM32_SPI6_TI_MODE SPI_TIMODE_DISABLE
#define STM32_SPI6_CRC SPI_CRCCALCULATION_DISABLE
#define STM32_SPI6_CRC_POL 10

/* RTC configuration */
#define STM32_RTC_CLOCK_SOURCE RCC_RTCCLKSOURCE_LSE
#define STM32_RTC_FORMAT RTC_HOURFORMAT_24
#define STM32_RTC_ASYNC_PREDIV 3
#define STM32_RTC_SYNC_PREDIV 8191
#define STM32_RTC_OUTPUT RTC_OUTPUT_DISABLE
#define STM32_RTC_OUTPUT_POL RTC_OUTPUT_POLARITY_HIGH
#define STM32_RTC_OUTPUT_TYPE RTC_OUTPUT_TYPE_OPENDRAIN

#endif
